## Data Preprocessing

- What is EDA?

- Process of understanding the data before building the ML model.

In [13]:
import numpy as np
import pandas as pd

In [33]:
# handling missing data

data = [['John', 25, 65], ['David', 15, 45], ['Alice', 70, 75], ['Bob', 20]]
df = pd.DataFrame(data, columns = ['Name', 'Age', 'Weight'])

In [34]:
df

    Name  Age  Weight
0   John   25    65.0
1  David   15    45.0
2  Alice   70    75.0
3    Bob   20     NaN

In [ ]:
df.info()

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum() # Total missing values

In [ ]:
# dropping the entire row

df1 = df.dropna()
df1

In [ ]:
# Substituting the missing value with another value, typically, with mean, median or mode.

# Imputation - technique of replacing missing values

In [ ]:
# Mean = Average (sum of values / number of values)

# Median = Middle Value
# ex: 1, 3, 4, 5, 6, 8, 90
# Mean = 117 / 7 = 17
# Median = 5

# Mode = most frequent value (ususally used with categorical data)

In [ ]:
df.describe()

In [20]:
from sklearn.impute import SimpleImputer

In [ ]:
help(SimpleImputer)

In [35]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')

In [36]:
imputer = imputer.fit(df[['Weight']])

In [37]:
df['Weight'] = imputer.transform(df[['Weight']])

In [38]:
df

    Name  Age  Weight
0   John   25    65.0
1  David   15    45.0
2  Alice   70    75.0
3    Bob   20    65.0

In [16]:
# Fill the missing values using PANDAS

data = [['John', 25, 65], ['David', 15, 45], ['Alice', 70, 75], ['Bob', 20]]
df2 = pd.DataFrame(data, columns = ['Name', 'Age', 'Weight'])

In [17]:
df2

    Name  Age  Weight
0   John   25    65.0
1  David   15    45.0
2  Alice   70    75.0
3    Bob   20     NaN

In [18]:
df2['Weight'] = df2['Weight'].fillna(df2['Weight'].mean())

In [19]:
df2

    Name  Age     Weight
0   John   25  65.000000
1  David   15  45.000000
2  Alice   70  75.000000
3    Bob   20  61.666667

In [ ]:
 help(pd.DataFrame.fillna) # To get full details of the methods

In [39]:
import matplotlib.pyplot as plt

In [ ]:
plt.boxplot(df['Age'])
plt.title('Age Outlier detection')
plt.show()

## handling Categorical Variables

In [ ]:
# Ex. Color -> red, green, yellow, blue (Nominal Catgorical variable)
# Ex. Size -> xs, s, m, l, xl (Ordinal Categorical variable)

In [41]:
df = pd.DataFrame(data = [['green', 'M', 10.5], ['yellow', 'S', 14.5], ['red', 'S', 15]], columns = ['Color', 'Size', 'Price'])

In [42]:
df

    Color Size  Price
0   green    M   10.5
1  yellow    S   14.5
2     red    S   15.0

In [43]:
df['Size'] = df['Size'].replace({'S':1,'M':2}) # can also use map

C:\Users\vinee\AppData\Local\Temp\ipykernel_30788\2726312849.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Size'] = df['Size'].replace({'S':1,'M':2}) # can also use map

In [44]:
df

    Color  Size  Price
0   green     2   10.5
1  yellow     1   14.5
2     red     1   15.0

In [ ]:
## One Hot Encoding (for nominal variables)

In [45]:
df1 = pd.get_dummies(df[['Color','Size','Price']])

In [46]:
df1

   Size  Price  Color_green  Color_red  Color_yellow
0     2   10.5         True      False         False
1     1   14.5        False      False          True
2     1   15.0        False       True         False

In [47]:
df2 = pd.get_dummies(df[['Color','Size','Price']], drop_first = True)
df2

   Size  Price  Color_red  Color_yellow
0     2   10.5      False         False
1     1   14.5      False          True
2     1   15.0       True         False

## SCALING

In [ ]:
# Scaling meaning bringing all numeric features to a similar scale:

#Why?
# one feature doesn't dominate 

# In predicting, house price, you have 2 features: bedroom, sqft size
# values in bedroom: 1,2,3,4
# values in sqft size: 1000, 2000, 5000

## 2 common scaling methods:

1. Standardization
2. Normalization

Standardization (Z-score approach): 

2, 6, 10 
Mean = 6 [(2+6+10)/3]
Std Dev = 4 

z = (x - mean)/std

org value -> z-value
2 -> -1
6 -> 0
10 -> 1

Another feature:

10000 -> -1
12000 -> 0
14000 -> 1

Mean = 12000
Std = 2000

Mean = Average
Standard Deviation = SQRT ((x1 - xm)^2 + (x2 - xm)^2.....)/n)

STD -> measurement of spread of the data

y = mx1 + c
x1 -> 10000, 12000, 11000

y = mx2 + c 
x -> 1,2,4,5

y = m1x1 + m2x2 +...

y = 1*10000 + 1+2 + 0
y = 10002

2. Normalization

This technique is used when we need fixed range of scaled values. Range is between 0 to 1.

x_normalized = (x - min)/ (max - min)

x -> x_normalized
10000 -> 0
12000 -> 0.5
14000 -> 1

In [ ]:
# Normalization is used in algorithms that use distance calculations.

In [ ]:
df2

In [48]:
from sklearn.preprocessing import StandardScaler # use MinMaxScaler for normalization

In [49]:
std = StandardScaler()

In [50]:
df2[['Size','Price']] = std.fit_transform(df2[['Size','Price']])

In [51]:
df2

       Size     Price  Color_red  Color_yellow
0  1.414214 -1.406930      False         False
1 -0.707107  0.579324      False          True
2 -0.707107  0.827606       True         False

## Assignment: Perform MinMaxScaler or Normalization on Size and Price Column